### ISSUE TITLE
Docker Container for Testing Datamonkey.org Locally

### ISSUE THREAD

**Issue by rdvelazquez** [rdvelazquez/datamonkey-js-server#1]

**Comment by rdvelazquez** [comment]
As discussed, we are going to work toward just being able to view hyphy-vision pages in datamonkey.

**Comment by stevenweaver** [comment]
We already use hyphy-vision in datamonkey. The docker container sounds pretty compelling. There is probably already a base image available somewhere that has a modern web stack, so you would just need to add checking out datamonkey-js, executing `make`, and configure `setup.js`.
